spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: admin #do not touch username
    password: ${SPRING_DATASOURCE_PASSWORD} #do not touch poassword

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true


  kakao:
    id: ${SPRING_KAKAO_ID}

  sql:
    init:
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      mode: always

server:
  servlet:
    session:
      timeout: 36000
