spring:
  datasource:
    initialization-mode: always
    url: jdbc:mariadb://localhost:3306/studywithme?serverTimezone=Asia/Seoul
    username: mine
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
    console:
      enable: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
      table-name: session

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true
    open-in-view: false

  profiles:
    include:
      - security

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  servlet:
    session:
      timeout: 36000