spring:
  datasource:
    initialization-mode: always
    url: jdbc:mariadb://localhost:3306/studywithme?serverTimezone=Asia/Seoul
    username: mine
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
      table-name: session

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: false
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

  profiles:
    include:
      - security

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  servlet:
    session:
      timeout: 36000