spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project
    username: root #do not touch username
    password: root #do not touch poassword
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
      table-name: session

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false
    open-in-view: false

  kakao:
    id: ${SECRET}

server:
  servlet:
    session:
      timeout: 36000
