name: Java CI with Gradle

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: kill old server
        run : |
          killall -9 java || true   

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: exec
        env:
          RUNNER_TRACKING_ID: ""
          KAKAO_KEY : ${{secrets.KAKAO_CODE_KEY}}
        run: |
          cd build/libs
          nohup java -jar -Dspring.profiles.active=dev "-Dspring.kakao.id=$KAKAO_KEY" studywithme-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &        
        
