name: StudyWithMe with Github Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: studywithme-cicd-bucket
  AWS_CODE_DEPLOY_APPLICATION: cicd-githubaction-studywithme
  AWS_CODE_DEPLOY_GROUP: cicd-studywithme-group


jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: set up jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: set yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.AWS_RDS_ENDPOINT }}
          spring.datasource.password: ${{ secrets.AWS_RDS_PASSWORD }}
          spring.kakao.id: ${{ secrets.KAKAO_CODE_KEY }}

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test -x asciidoctor


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: upload to s3
        run: |
          aws deploy push \
            --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} \
            --ignore-hidden-files \
            --s3-location s3://$AWS_S3_BUCKET/$GITHUB_SHA.zip \
            --source .


      - name: deploy to ec2 using codedeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
            --s3-location bucket=$AWS_S3_BUCKET,key=$GITHUB_SHA.zip,bundleType=zip